name: Translate README

on:
  push:
    paths:
      - 'README.md'
  workflow_dispatch:  # Allows manual triggering from GitHub Actions tab

jobs:
  translate:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        lang: [es, zh-CN, ja, fr]   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Translate README to ${{ matrix.lang }}
        uses: dephraiim/translate-readme@main
        with:
          LANG: ${{ matrix.lang }}
