name: Translate README

on:
  push:
    paths:
      - 'README.md'

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Translate README (readme-translator)
        uses: dephraiim/translate-readme@main
        with:
          LANG: es,zh-CN,ja,fr
